const $=s=>document.querySelector(s);
const pages=[...document.querySelectorAll(".page")];
let authMode="login",navigationReady=false;
const titles={home:["BIS SAHAYAK AI","Business command center"],assistant:["AI ASSISTANT","Your intelligent guide"],documents:["DOCUMENT VAULT","Business documents"],compliance:["COMPLIANCE","What needs attention?"],sources:["SOURCES & TOOLS","Verify and investigate"]};
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function validPage(id){return Object.prototype.hasOwnProperty.call(titles,id)}
function go(id){if(!validPage(id))id="home";if(location.hash!=="#"+id)location.hash=id;else showPage(id,false);closeSidebar()}
function showPage(id,updateHash=true){if(!validPage(id))id="home";pages.forEach(p=>p.classList.toggle("activePage",p.id===id));document.querySelectorAll("[data-page]").forEach(b=>{b.classList.toggle("active",b.dataset.page===id);b.setAttribute("aria-current",b.dataset.page===id?"page":"false")});$("#pageKicker").textContent=titles[id][0];$("#pageTitle").textContent=titles[id][1];if(updateHash&&location.hash!=="#"+id)history.pushState({page:id},"","#"+id);if(id==="documents")loadDocs();if(id==="compliance")loadCompliance();if(id==="sources")loadSources();window.scrollTo({top:0,behavior:navigationReady?"smooth":"auto"})}
function handleRoute(){const id=decodeURIComponent(location.hash.replace(/^#/,""))||"home";showPage(validPage(id)?id:"home",false);navigationReady=true}
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.page)));
window.addEventListener("hashchange",handleRoute);window.addEventListener("popstate",handleRoute);
function toggleSidebar(){const open=$("#sidebar").classList.toggle("open");$("#mobileOverlay").classList.toggle("show",open);$("#menuBtn").setAttribute("aria-expanded",String(open))}
function closeSidebar(){$("#sidebar").classList.remove("open");$("#mobileOverlay").classList.remove("show");if($("#menuBtn"))$("#menuBtn").setAttribute("aria-expanded","false")}
function quick(q){go("assistant");setTimeout(()=>send(q),180)}
function add(text,type="bot",sources=[]){const d=document.createElement("div");d.className="bubble "+type;const sh=sources.length?`<small>Sources: ${sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title||"Source")}</a>`).join(" • ")}</small>`:"";d.innerHTML=`<b>${type==="user"?"You":"BIS Sahayak"}</b><p>${esc(text).replace(/\n/g,"<br>")}</p>${sh}`;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
async function send(q){if(!q)return;add(q,"user");$("#chatInput").value="";add("Processing…");const waiting=$("#messages").lastElementChild;try{const r=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,language:$("#lang").value,live:$("#liveToggle").checked})});const d=await r.json();waiting?.remove();add(d.answer||d.error||"No answer returned.","bot",d.sources||[])}catch{waiting?.remove();add("Connection unavailable. Please check that the BIS Sahayak backend is running.")}}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();send($("#chatInput").value.trim())});
$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.theme=document.body.classList.contains("dark")?"dark":"light"});if(localStorage.theme==="dark")document.body.classList.add("dark");
function authHeaders(){const t=localStorage.bis_token;return t?{Authorization:"Bearer "+t}:{}}
async function loadDocs(){const t=$("#docs");try{const r=await fetch("/api/dashboard",{headers:authHeaders()});if(!r.ok){t.innerHTML='<tr><td colspan="4">Sign in to use the private document vault.</td></tr>';$("#docStats").innerHTML="";return}const d=await r.json();$("#docStats").innerHTML=`<div><b>${d.summary.valid}</b><span>Valid / active</span></div><div><b>${d.summary.renew}</b><span>Renew soon</span></div><div><b>${d.summary.action}</b><span>Actions pending</span></div>`;t.innerHTML=d.documents.map(x=>{const renew=x.expiry&&new Date(x.expiry)<new Date(Date.now()+30*864e5);return `<tr><td>${esc(x.name)}</td><td>${esc(x.status)}</td><td>${x.expiry?new Date(x.expiry).toLocaleDateString():"Not set"}</td><td>${renew?"Review / renew":"Monitor"}</td></tr>`}).join("")||'<tr><td colspan="4">No documents registered yet.</td></tr>'}catch{t.innerHTML='<tr><td colspan="4">Unable to load documents.</td></tr>'}}
$("#file").addEventListener("change",async()=>{const f=$("#file").files[0];if(!f)return;if(!localStorage.bis_token){$("#file").value="";openAuth();return}try{const fd=new FormData();fd.append("document",f);const r=await fetch("/api/documents/upload",{method:"POST",headers:authHeaders(),body:fd});const d=await r.json();alert(d.message||d.error||"Upload complete.");if(r.ok)loadDocs()}catch{alert("Document upload failed. Please check the backend.")}finally{$("#file").value=""}});
async function loadCompliance(){try{const r=await fetch("/api/dashboard",{headers:authHeaders()});if(!r.ok){$("#tasks").innerHTML="<p>Sign in to use compliance tracking.</p>";$("#compStats").innerHTML="";return}const d=await r.json();$("#compStats").innerHTML=`<div><b>${d.summary.action}</b><span>Needs action</span></div><div><b>${d.summary.renew}</b><span>Documents renewing soon</span></div><div><b>${d.queries}</b><span>AI interactions</span></div>`;$("#tasks").innerHTML=d.compliance.map(x=>`<article class="task"><span class="status">${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.action||"Review requirement and verify current source.")}</p><small>Due: ${x.dueDate?new Date(x.dueDate).toLocaleDateString():"Not set"}</small></article>`).join("")||"<p>No compliance tasks yet. Add one to start tracking.</p>"}catch{$("#tasks").innerHTML="<p>Unable to load compliance data.</p>"}}
async function addCompliance(){if(!localStorage.bis_token){openAuth();return}const title=prompt("Compliance task name");if(!title)return;const due=prompt("Due date YYYY-MM-DD (optional)");try{const r=await fetch("/api/compliance",{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify({title,status:"review",dueDate:due,category:"business",action:"Review requirement and verify the current official source."})});if(!r.ok){const d=await r.json().catch(()=>({}));alert(d.error||"Could not create task.");return}loadCompliance()}catch{alert("Could not create task.")}}
async function loadSources(){try{const r=await fetch("/api/sources");const d=await r.json();$("#sourceGrid").innerHTML=d.map(x=>`<article class="source"><small>${esc(x.kind)}</small><h3>${esc(x.title)}</h3><p>Official source for verification.</p><a href="${esc(x.url)}" target="_blank" rel="noopener">Open source ↗</a></article>`).join("")}catch{$("#sourceGrid").innerHTML="<p>Unable to load sources.</p>"}}
async function liveSearch(){const q=prompt("What current information do you want to search?");if(!q)return;try{const r=await fetch("/api/ai/live-search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q})});const d=await r.json();$("#liveResults").innerHTML=d.results?.length?d.results.map(x=>`<div><b>${esc(x.title||"Live result")}</b><p>${esc(x.snippet||x.description||"")}</p>${x.url?`<a target="_blank" rel="noopener" href="${esc(x.url)}">Open ↗</a>`:""}</div>`).join(""):"<div>No live-search connector is configured. Official BIS links above remain available.</div>"}catch{$("#liveResults").innerHTML="<div>Live search is currently unavailable.</div>"}}
function openAuth(){authMode="login";$("#auth").classList.add("show");updateAuth();setTimeout(()=>$("#email").focus(),50)}
function closeAuth(){$("#auth").classList.remove("show")}
function toggleAuth(){authMode=authMode==="login"?"register":"login";updateAuth()}
function updateAuth(){const r=authMode==="register";$("#authTitle").textContent=r?"Create an account":"Sign in";$("#name").hidden=!r;$("#name").style.display=r?"":"none";$("#password").autocomplete=r?"new-password":"current-password";$("#authMsg").textContent=""}
async function submitAuth(){const r=authMode==="register",body={email:$("#email").value.trim(),password:$("#password").value};if(r)body.name=$("#name").value.trim();if(!body.email||!body.password||(r&&!body.name)){$("#authMsg").textContent="Please complete all required fields.";return}try{const x=await fetch(r?"/api/auth/register":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await x.json();$("#authMsg").textContent=d.error||(d.token?"Signed in successfully.":"Request completed.");if(d.token){localStorage.bis_token=d.token;closeAuth();loadDocs();loadCompliance()}}catch{$("#authMsg").textContent="Authentication service unavailable."}}
$("#auth").addEventListener("click",e=>{if(e.target.id==="auth")closeAuth()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeAuth();closeSidebar()}});
handleRoute();loadSources();fetch("/api/health").then(r=>r.json()).then(d=>{$("#connection").textContent=d.onlineAI?"Online AI ready":d.ollama?"Local AI ready":"Backend connected"}).catch(()=>{$("#connection").textContent="Connection unavailable"});
